site_name: NixOS Öğreniyoruz - Murat Çabuk
site_url: https://nixogreniyoruz.kavakci.dev
docs_dir: src
repo_url: https://github.com/LinuxTurkey/nix-ogreniyoruz
repo_name: LinuxTurkey/nix-ogreniyoruz
edit_uri: edit/main/src/
plugins: 
  - social:
      cards_layout_options:
        logo: assets/logo.png
  - search
  - offline
markdown_extensions: 
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
theme:
  name: material
  icon:
    logo: simple/nixos
    annotation: material/circle-medium
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.prune 
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  language: tr
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: "#7EBAE4"
      accent: "#7EBAE4"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: "#7EBAE4"
      accent: "#7EBAE4"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
nav:
  - NixOS: README.md
  - Nix Dili:
    - Nix Dili ve Özellikleri: nix_lang/01_nix_dili_ve_ozellikleri.md
    - Nix Dili ile İlgili Alıştırmalar: nix_lang/02_nix_dili_alistirmalari.md
    - Nix Dilinde Gömülü Fonksiyonlar: nix_lang/03_nix_dili_gomulu.md
  - Nix Paket Yöneticisi:
    - Nix Paket Yöneticisi: nix_package/nix_paket_yoneticisi.md
    - Nix Shell ve Profile: nix_package/nix_shell_ve_profile.md
    - Nix Flake Nedir?: nix_package/nix_flake_nedir.md
    - Birden Çok Paketi Aynı Repo Üzeriden Yayınlamak: nix_package/birden_cok_paketi_ayni_repo_uzerinden_yayinlamak.md
    - Override ve Overlay: nix_package/override_ve_overlay.md
    - Developer ve Profile Ortamları Oluşturmak: nix_package/developer_ve_profile_ortamlari_olusturmak.md
  - Sonrası:
    - Nix ile NixOS Konfigürasyonu: nix_ile_nix_konfigurasyonu.md
    - Module ve Option Kullanımı: module_ve_option_kullanimi.md
    - NixOS Kurulumu ve Konfigürasyonu: nixos_kurulumu_ve_konfigurasyonu.md
    - NixOS'u Cloud ve Uzak Ortamlara Deploy Etmek: nixos_cloud_ve_uzak_ortam.md
