[project]
name = "nix-ogreniyoruz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material[imaging]>=9.6.20",
]
